builders:
  realm_named_object_builder:
    import: "package:realm_named_generator/realm_named_generator.dart"    
    builder_factories: ["generateRealmObjects"]
    build_extensions: { ".dart": [".realm.dart"] }
    auto_apply: dependents
    build_to: source
